@startuml

component "LogicMonitorBuilder"
component "LogicMonitor"
component "LogicMonitorHook" <<interface>>
component "LogicMonitorState"

LogicMonitorBuilder ..> LogicMonitor : build
LogicMonitor ..> LogicMonitorHook : call on change
LogicMonitor ..> LogicMonitorState : transition between

@enduml
