' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
title Alive Monitoring

autonumber "<b>[000]"

participant "Launch Manager" as LM
participant "SCORE Application" as App

activate LM
activate App

note over LM, App
    Application is already running and alive supervision is successful
end note

loop
    App -> LM : ReportAlive()
end

...

[-> LM : Activate Run Target (RunTarget1)

note over LM, App
    The application is not configured to run as part of the new Run Target and will be shutdown
end note

LM -> App : SIGTERM
LM -> LM : Deactivate Alive Supervision, Start shutdown timeout monitoring

...

alt #pink Application did not terminate within the shutdown timeout

LM -> LM : Application shutdown timeout expired
LM -> App : SIGKILL
end alt

destroy App

deactivate App
deactivate LM
@enduml
