' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml "Abstract Launch Manager Configuration Structure"

class LaunchManager
{

}

class LaunchConfiguration
{
}

LaunchManager "1" --> "1" LaunchConfiguration
LaunchConfiguration "1" -d-> "1" RunTargetConfig : initial Run Target
LaunchConfiguration "1" -d-> "1" RunTargetConfig : fallback Run Target

class ConfigFile
{

}

LaunchConfiguration "1" *--> "1..*" ConfigFile

class ComponentConfig {
'''Component Properties'''
  + {field} component name
  + {field} binary name
  + {field} type (e.g. Reporting process, native process, supervised process)
  + {field} self terminating (true/false)
  + {field} process arguments
'''Deployment Properties'''
  + {field} binary dir
  + {field} working dir
  + {field} ready timeout
  + {field} shutdown timeout
  + {field} environment variables
}

class RunTargetConfig {
    + {field} Run Target name
    + {field} transition timeout
}

class RunTargetRecoveryAction as "RunTarget\nRecoveryAction" {}

RunTargetConfig "1" -d-> "1..*" RunTargetRecoveryAction

ConfigFile "1" *-d-> "1..*" ComponentConfig
ConfigFile "1" *-d-> "1..*" RunTargetConfig

RunTargetConfig "1" -l-> "1..*" RunTargetConfig : \ndependency
RunTargetConfig "1" -r-> "1..*" ComponentConfig : dependency

class AliveSupervision {
  + {field} expected alive notification interval
  + {field} expected alive notification count (min/max)
  + {field} failure tolerance limit
}

class ComponentRecoveryAction as "Component\nRecoveryAction" {}
class SafeStateRecoveryAction as "SafeState\nRecoveryAction" {}
class ComponentRestartRecoveryAction as "ComponentRestart\nRecoveryAction" {
   + {field} retry count (how many times to try)
   + {field} wait time (before the component can be started again)
}
SafeStateRecoveryAction -u-|> ComponentRecoveryAction
ComponentRestartRecoveryAction -u-|> ComponentRecoveryAction

class SwitchRunTargetRecoveryAction as "SwitchRunTarget\nRecoveryAction" {
   + {field} next Run Target
}
SwitchRunTargetRecoveryAction -u-|> RunTargetRecoveryAction
SwitchRunTargetRecoveryAction -u-|> ComponentRecoveryAction

class ReadyCondition {}

class FileStateCondition {
  + {field} state (exists, not exists)
  + {field} polling interval
}

class ProcessStateCondition {
  + {field} Running/Terminated
}

FileStateCondition -up-|> ReadyCondition
ProcessStateCondition -up-|> ReadyCondition

class SandboxConfig {
  + {field} UID
  + {field} GID
  + {field} supplementary groups
  + {field} runmask
  + {field} priority
  + {field} ability
  + {field} security
  + {field} stdin
  + {field} stdout
  + {field} stderr
  + {field} aslr
  + {field} rlimits
}

ComponentConfig "1" -l-> "1..*" ComponentConfig: dependency
ComponentConfig "1" *-d-> "1" ReadyCondition
ComponentConfig "1" *-d-> "1" AliveSupervision
ComponentConfig "1" *--> "1" SandboxConfig
ComponentConfig "1" *--> "1" ComponentRecoveryAction

@enduml
