' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
title Launch Manager - Run Components in Parallel

autonumber "<b>[00]"

participant "Launch Manager" as LM
participant "OS (kernel)" as kernel
participant "Reporting App 1" as app1
participant "Reporting App 2" as app2
activate LM

LM -> LM: analyze current state
LM -> LM: determine transition plan

LM -> kernel: Start Reporting App 1
LM -> kernel: Start Reporting App 2
kernel -> app1 **: Start
kernel -> app2 **: Start

activate app1
activate app2

app1 -> app1: Internal User app initialization
app1 -> LM: signal ready state via Lifecycle API
app2 -> app2: Internal User app initialization
app2 -> LM: signal ready state via Lifecycle API
...
@enduml
