' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
title Launch Manager - "Normal" Shutdown

autonumber "<b>[00]"

participant "Launch Manager" as LM
participant "OS (kernel)" as kernel
participant "setup_filesystems.sh" as fs
participant "random" as ran
participant "app1" as app1

activate LM
activate app1
activate ran

note over LM,app1
The Run Target "Running" is currently active.
end note

[-> LM : SIGTERM
LM -> LM : Determine transition plan to Run Target "Off"

ref over LM, app1
  Transition to Run Target "Off":
  all Components are terminated in dependency order.
  See //Launch Manager - Component Termination//.
end ref

LM -> LM : Run Target "Off" successfully activated
destroy app1
destroy ran

LM -> LM : Deinitialize, free resources
[<- LM : exit
destroy LM
...
@enduml
