' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
title Launch Manager - Crash Recovery

autonumber "<b>[00]"

participant "Launch Manager" as LM
participant "OS (kernel)" as kernel

participant "setup_filesystems.sh" as fs
participant "random" as ran
participant "app1" as app1

activate LM
activate ran
activate app1

...

note over LM,app1
Run Target "Running" successfully active
end note

app1 -> app1: Random crash.
app1 -> kernel: Terminate.
destroy app1
kernel -> LM: Process terminated.

LM -> LM: Analyze current state.
LM -> LM: Determine transition plan.\nA recovery action will be executed

alt App1 has Recovery Action Restart configured

LM -> LM: Start Restart RecoveryAction for app1
LM -> kernel: start app1
kernel -> app1 ++ : start
app1 -> app1 : Initialization
app1 -> LM : Report Running via Lifecycle API
LM -> LM: Recovery Action done
deactivate app1

else App1 has Recovery Action Switch Run Target configured

LM -> LM: Determine Transition Plan to new RunTarget
LM -> LM: Switch Run Target.

ref over LM, app1
  Activation of the new Run Target:
  Components are terminated and started in dependency order,
  see other sequence diagrams for the detailed sequence.
  app1 is restarted if it is configured for the new Run Target.
end ref

end alt

...

@enduml
