' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml Process State Machine

[*] -d-> Terminated
Terminated -> Starting : Process started (fork())
Starting --> Running : The process reported Running state\n(non-reporting process transitions\ndirectly to Running)
Running --> Terminating : Launch Manager sends SIGTERM
Terminating --> Terminated : Process terminated /\n<color:red>SIGKILL in case of shutdown timeout</color>
Starting -[#red]-> Terminated : <color:red>Process crashed</color>\n<color:red>or is forcefully terminated</color>\n<color:red>due to activation timeout</color>
Running -[#red]-> Terminated : <color:red>Process crashed</color>

legend right
	Error cases are highlighted in <color:red>red</color>.
endlegend

@enduml
