// Auto-generated by cbindgen. Do not edit.

#ifndef ALIVE_MONITOR_FFI_H
#define ALIVE_MONITOR_FFI_H

#include <cstdint>

struct AliveMonitor;

using AliveMonitorFfi = AliveMonitor;

extern "C"
{
    AliveMonitorFfi *create_alive_monitor(uint64_t heartbeat_interval);

    void alive_monitor_free(AliveMonitorFfi *handle);

    void configure_minimum_time(AliveMonitorFfi *handle, uint64_t minimum_time_ms);

    void keep_alive(AliveMonitorFfi *handle);

}  // extern "C"

#endif  // ALIVE_MONITOR_FFI_H
