// Auto-generated by cbindgen. Do not edit.

#ifndef EXAMPLES_COMMON_UTILS_H
#define EXAMPLES_COMMON_UTILS_H

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>
#include <ostream>

struct SignalHandleData;

extern "C"
{
    uint64_t read_heartbeat_interval_c();

    void read_app_name_c(char *buf, uint16_t buf_len);

    SignalHandleData *signal_handle_data_create();

    void signal_handle_data_free(SignalHandleData *ptr);

    void signal_handle_data_set_shutdown(SignalHandleData *ptr, bool value);

    bool signal_handle_data_is_shutdown_requested(SignalHandleData *ptr);

    void signal_handler_loop_c(SignalHandleData *ptr);

    void notify_ready_c();

    void run_app_c();

}  // extern "C"

#endif  // EXAMPLES_COMMON_UTILS_H
