@startuml

package "Launch Manager" as LM { 
    [Configuration manager] as CM
    [Process Group manager] as PGM
    [OS abstraction layer (OSAL)] as OSAL

    ' using invisible links (or links in white color)
    ' to enforce top to bottom layout
    CM -[#white]d-> PGM
    PGM -[#white]d-> OSAL
}

[Control client lib] as CC
[Lifecycle client lib] as LC

LC <-r-> LM
CC <--> LM

@enduml
