# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

alias(
    name = "health_monitoring_cc",
    actual = "//score/health_monitor/src/cpp:health_monitoring_cc",
    visibility = ["//visibility:public"],
)

alias(
    name = "health_monitoring_cc_interface",
    actual = "//score/health_monitor/src/cpp:health_monitoring_cc_interface",
    visibility = ["//visibility:public"],
)

alias(
    name = "health_monitoring_cc_mock",
    actual = "//score/health_monitor/src/cpp:health_monitoring_cc_mock",
    visibility = ["//visibility:public"],
)

alias(
    name = "health_monitoring_rust",
    actual = "//score/health_monitor/src/rust:health_monitoring_lib",
    visibility = ["//visibility:public"],
)
