// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NEWLMFLATCFG_SCORE_LAUNCH_MANAGER_CONFIG_FB_H_
#define FLATBUFFERS_GENERATED_NEWLMFLATCFG_SCORE_LAUNCH_MANAGER_CONFIG_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace score {
namespace launch_manager {
namespace config {
namespace fb {

struct ComponentAliveSupervision;
struct ComponentAliveSupervisionBuilder;

struct ApplicationProfile;
struct ApplicationProfileBuilder;

struct ReadyCondition;
struct ReadyConditionBuilder;

struct ComponentProperties;
struct ComponentPropertiesBuilder;

struct RestartAction;
struct RestartActionBuilder;

struct SwitchRunTargetAction;
struct SwitchRunTargetActionBuilder;

struct EnvironmentalVariable;
struct EnvironmentalVariableBuilder;

struct Sandbox;
struct SandboxBuilder;

struct DeploymentConfig;
struct DeploymentConfigBuilder;

struct RunTarget;
struct RunTargetBuilder;

struct Component;
struct ComponentBuilder;

struct AliveSupervision;
struct AliveSupervisionBuilder;

struct Watchdog;
struct WatchdogBuilder;

struct FallbackRunTarget;
struct FallbackRunTargetBuilder;

struct LaunchManagerConfig;
struct LaunchManagerConfigBuilder;

enum ApplicationType : int8_t {
  ApplicationType_Native = 0,
  ApplicationType_Reporting = 1,
  ApplicationType_Reporting_And_Supervised = 2,
  ApplicationType_State_Manager = 3,
  ApplicationType_MIN = ApplicationType_Native,
  ApplicationType_MAX = ApplicationType_State_Manager
};

inline const ApplicationType (&EnumValuesApplicationType())[4] {
  static const ApplicationType values[] = {
    ApplicationType_Native,
    ApplicationType_Reporting,
    ApplicationType_Reporting_And_Supervised,
    ApplicationType_State_Manager
  };
  return values;
}

inline const char * const *EnumNamesApplicationType() {
  static const char * const names[5] = {
    "Native",
    "Reporting",
    "Reporting_And_Supervised",
    "State_Manager",
    nullptr
  };
  return names;
}

inline const char *EnumNameApplicationType(ApplicationType e) {
  if (::flatbuffers::IsOutRange(e, ApplicationType_Native, ApplicationType_State_Manager)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesApplicationType()[index];
}

enum ProcessState : int8_t {
  ProcessState_Running = 0,
  ProcessState_Terminated = 1,
  ProcessState_MIN = ProcessState_Running,
  ProcessState_MAX = ProcessState_Terminated
};

inline const ProcessState (&EnumValuesProcessState())[2] {
  static const ProcessState values[] = {
    ProcessState_Running,
    ProcessState_Terminated
  };
  return values;
}

inline const char * const *EnumNamesProcessState() {
  static const char * const names[3] = {
    "Running",
    "Terminated",
    nullptr
  };
  return names;
}

inline const char *EnumNameProcessState(ProcessState e) {
  if (::flatbuffers::IsOutRange(e, ProcessState_Running, ProcessState_Terminated)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProcessState()[index];
}

enum RecoveryAction : uint8_t {
  RecoveryAction_NONE = 0,
  RecoveryAction_RestartAction = 1,
  RecoveryAction_SwitchRunTargetAction = 2,
  RecoveryAction_MIN = RecoveryAction_NONE,
  RecoveryAction_MAX = RecoveryAction_SwitchRunTargetAction
};

inline const RecoveryAction (&EnumValuesRecoveryAction())[3] {
  static const RecoveryAction values[] = {
    RecoveryAction_NONE,
    RecoveryAction_RestartAction,
    RecoveryAction_SwitchRunTargetAction
  };
  return values;
}

inline const char * const *EnumNamesRecoveryAction() {
  static const char * const names[4] = {
    "NONE",
    "RestartAction",
    "SwitchRunTargetAction",
    nullptr
  };
  return names;
}

inline const char *EnumNameRecoveryAction(RecoveryAction e) {
  if (::flatbuffers::IsOutRange(e, RecoveryAction_NONE, RecoveryAction_SwitchRunTargetAction)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRecoveryAction()[index];
}

template<typename T> struct RecoveryActionTraits {
  static const RecoveryAction enum_value = RecoveryAction_NONE;
};

template<> struct RecoveryActionTraits<score::launch_manager::config::fb::RestartAction> {
  static const RecoveryAction enum_value = RecoveryAction_RestartAction;
};

template<> struct RecoveryActionTraits<score::launch_manager::config::fb::SwitchRunTargetAction> {
  static const RecoveryAction enum_value = RecoveryAction_SwitchRunTargetAction;
};

template <bool B = false>
bool VerifyRecoveryAction(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, RecoveryAction type);
template <bool B = false>
bool VerifyRecoveryActionVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct ComponentAliveSupervision FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ComponentAliveSupervisionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REPORTING_CYCLE = 4,
    VT_FAILED_CYCLES_TOLERANCE = 6,
    VT_MIN_INDICATIONS = 8,
    VT_MAX_INDICATIONS = 10
  };
  double reporting_cycle() const {
    return GetField<double>(VT_REPORTING_CYCLE, 0.0);
  }
  uint32_t failed_cycles_tolerance() const {
    return GetField<uint32_t>(VT_FAILED_CYCLES_TOLERANCE, 0);
  }
  ::flatbuffers::Optional<uint32_t> min_indications() const {
    return GetOptional<uint32_t, uint32_t>(VT_MIN_INDICATIONS);
  }
  ::flatbuffers::Optional<uint32_t> max_indications() const {
    return GetOptional<uint32_t, uint32_t>(VT_MAX_INDICATIONS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_REPORTING_CYCLE, 8) &&
           VerifyField<uint32_t>(verifier, VT_FAILED_CYCLES_TOLERANCE, 4) &&
           VerifyField<uint32_t>(verifier, VT_MIN_INDICATIONS, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_INDICATIONS, 4) &&
           verifier.EndTable();
  }
};

struct ComponentAliveSupervisionBuilder {
  typedef ComponentAliveSupervision Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_reporting_cycle(double reporting_cycle) {
    fbb_.AddElement<double>(ComponentAliveSupervision::VT_REPORTING_CYCLE, reporting_cycle, 0.0);
  }
  void add_failed_cycles_tolerance(uint32_t failed_cycles_tolerance) {
    fbb_.AddElement<uint32_t>(ComponentAliveSupervision::VT_FAILED_CYCLES_TOLERANCE, failed_cycles_tolerance, 0);
  }
  void add_min_indications(uint32_t min_indications) {
    fbb_.AddElement<uint32_t>(ComponentAliveSupervision::VT_MIN_INDICATIONS, min_indications);
  }
  void add_max_indications(uint32_t max_indications) {
    fbb_.AddElement<uint32_t>(ComponentAliveSupervision::VT_MAX_INDICATIONS, max_indications);
  }
  explicit ComponentAliveSupervisionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ComponentAliveSupervision> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ComponentAliveSupervision>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ComponentAliveSupervision> CreateComponentAliveSupervision(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double reporting_cycle = 0.0,
    uint32_t failed_cycles_tolerance = 0,
    ::flatbuffers::Optional<uint32_t> min_indications = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint32_t> max_indications = ::flatbuffers::nullopt) {
  ComponentAliveSupervisionBuilder builder_(_fbb);
  builder_.add_reporting_cycle(reporting_cycle);
  if(max_indications) { builder_.add_max_indications(*max_indications); }
  if(min_indications) { builder_.add_min_indications(*min_indications); }
  builder_.add_failed_cycles_tolerance(failed_cycles_tolerance);
  return builder_.Finish();
}

struct ApplicationProfile FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ApplicationProfileBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_APPLICATION_TYPE = 4,
    VT_IS_SELF_TERMINATING = 6,
    VT_ALIVE_SUPERVISION = 8
  };
  score::launch_manager::config::fb::ApplicationType application_type() const {
    return static_cast<score::launch_manager::config::fb::ApplicationType>(GetField<int8_t>(VT_APPLICATION_TYPE, 0));
  }
  bool is_self_terminating() const {
    return GetField<uint8_t>(VT_IS_SELF_TERMINATING, 0) != 0;
  }
  const score::launch_manager::config::fb::ComponentAliveSupervision *alive_supervision() const {
    return GetPointer<const score::launch_manager::config::fb::ComponentAliveSupervision *>(VT_ALIVE_SUPERVISION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_APPLICATION_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_SELF_TERMINATING, 1) &&
           VerifyOffset(verifier, VT_ALIVE_SUPERVISION) &&
           verifier.VerifyTable(alive_supervision()) &&
           verifier.EndTable();
  }
};

struct ApplicationProfileBuilder {
  typedef ApplicationProfile Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_application_type(score::launch_manager::config::fb::ApplicationType application_type) {
    fbb_.AddElement<int8_t>(ApplicationProfile::VT_APPLICATION_TYPE, static_cast<int8_t>(application_type), 0);
  }
  void add_is_self_terminating(bool is_self_terminating) {
    fbb_.AddElement<uint8_t>(ApplicationProfile::VT_IS_SELF_TERMINATING, static_cast<uint8_t>(is_self_terminating), 0);
  }
  void add_alive_supervision(::flatbuffers::Offset<score::launch_manager::config::fb::ComponentAliveSupervision> alive_supervision) {
    fbb_.AddOffset(ApplicationProfile::VT_ALIVE_SUPERVISION, alive_supervision);
  }
  explicit ApplicationProfileBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ApplicationProfile> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ApplicationProfile>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ApplicationProfile> CreateApplicationProfile(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    score::launch_manager::config::fb::ApplicationType application_type = score::launch_manager::config::fb::ApplicationType_Native,
    bool is_self_terminating = false,
    ::flatbuffers::Offset<score::launch_manager::config::fb::ComponentAliveSupervision> alive_supervision = 0) {
  ApplicationProfileBuilder builder_(_fbb);
  builder_.add_alive_supervision(alive_supervision);
  builder_.add_is_self_terminating(is_self_terminating);
  builder_.add_application_type(application_type);
  return builder_.Finish();
}

struct ReadyCondition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReadyConditionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROCESS_STATE = 4
  };
  ::flatbuffers::Optional<score::launch_manager::config::fb::ProcessState> process_state() const {
    return GetOptional<int8_t, score::launch_manager::config::fb::ProcessState>(VT_PROCESS_STATE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_PROCESS_STATE, 1) &&
           verifier.EndTable();
  }
};

struct ReadyConditionBuilder {
  typedef ReadyCondition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_process_state(score::launch_manager::config::fb::ProcessState process_state) {
    fbb_.AddElement<int8_t>(ReadyCondition::VT_PROCESS_STATE, static_cast<int8_t>(process_state));
  }
  explicit ReadyConditionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReadyCondition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReadyCondition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReadyCondition> CreateReadyCondition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Optional<score::launch_manager::config::fb::ProcessState> process_state = ::flatbuffers::nullopt) {
  ReadyConditionBuilder builder_(_fbb);
  if(process_state) { builder_.add_process_state(*process_state); }
  return builder_.Finish();
}

struct ComponentProperties FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ComponentPropertiesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BINARY_NAME = 4,
    VT_APPLICATION_PROFILE = 6,
    VT_DEPENDS_ON = 8,
    VT_PROCESS_ARGUMENTS = 10,
    VT_READY_CONDITION = 12
  };
  const ::flatbuffers::String *binary_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BINARY_NAME);
  }
  const score::launch_manager::config::fb::ApplicationProfile *application_profile() const {
    return GetPointer<const score::launch_manager::config::fb::ApplicationProfile *>(VT_APPLICATION_PROFILE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *depends_on() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DEPENDS_ON);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *process_arguments() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_PROCESS_ARGUMENTS);
  }
  const score::launch_manager::config::fb::ReadyCondition *ready_condition() const {
    return GetPointer<const score::launch_manager::config::fb::ReadyCondition *>(VT_READY_CONDITION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BINARY_NAME) &&
           verifier.VerifyString(binary_name()) &&
           VerifyOffsetRequired(verifier, VT_APPLICATION_PROFILE) &&
           verifier.VerifyTable(application_profile()) &&
           VerifyOffset(verifier, VT_DEPENDS_ON) &&
           verifier.VerifyVector(depends_on()) &&
           verifier.VerifyVectorOfStrings(depends_on()) &&
           VerifyOffset(verifier, VT_PROCESS_ARGUMENTS) &&
           verifier.VerifyVector(process_arguments()) &&
           verifier.VerifyVectorOfStrings(process_arguments()) &&
           VerifyOffsetRequired(verifier, VT_READY_CONDITION) &&
           verifier.VerifyTable(ready_condition()) &&
           verifier.EndTable();
  }
};

struct ComponentPropertiesBuilder {
  typedef ComponentProperties Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_binary_name(::flatbuffers::Offset<::flatbuffers::String> binary_name) {
    fbb_.AddOffset(ComponentProperties::VT_BINARY_NAME, binary_name);
  }
  void add_application_profile(::flatbuffers::Offset<score::launch_manager::config::fb::ApplicationProfile> application_profile) {
    fbb_.AddOffset(ComponentProperties::VT_APPLICATION_PROFILE, application_profile);
  }
  void add_depends_on(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> depends_on) {
    fbb_.AddOffset(ComponentProperties::VT_DEPENDS_ON, depends_on);
  }
  void add_process_arguments(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> process_arguments) {
    fbb_.AddOffset(ComponentProperties::VT_PROCESS_ARGUMENTS, process_arguments);
  }
  void add_ready_condition(::flatbuffers::Offset<score::launch_manager::config::fb::ReadyCondition> ready_condition) {
    fbb_.AddOffset(ComponentProperties::VT_READY_CONDITION, ready_condition);
  }
  explicit ComponentPropertiesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ComponentProperties> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ComponentProperties>(end);
    fbb_.Required(o, ComponentProperties::VT_BINARY_NAME);
    fbb_.Required(o, ComponentProperties::VT_APPLICATION_PROFILE);
    fbb_.Required(o, ComponentProperties::VT_READY_CONDITION);
    return o;
  }
};

inline ::flatbuffers::Offset<ComponentProperties> CreateComponentProperties(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> binary_name = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::ApplicationProfile> application_profile = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> depends_on = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> process_arguments = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::ReadyCondition> ready_condition = 0) {
  ComponentPropertiesBuilder builder_(_fbb);
  builder_.add_ready_condition(ready_condition);
  builder_.add_process_arguments(process_arguments);
  builder_.add_depends_on(depends_on);
  builder_.add_application_profile(application_profile);
  builder_.add_binary_name(binary_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ComponentProperties> CreateComponentPropertiesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *binary_name = nullptr,
    ::flatbuffers::Offset<score::launch_manager::config::fb::ApplicationProfile> application_profile = 0,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *depends_on = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *process_arguments = nullptr,
    ::flatbuffers::Offset<score::launch_manager::config::fb::ReadyCondition> ready_condition = 0) {
  auto binary_name__ = binary_name ? _fbb.CreateString(binary_name) : 0;
  auto depends_on__ = depends_on ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*depends_on) : 0;
  auto process_arguments__ = process_arguments ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*process_arguments) : 0;
  return score::launch_manager::config::fb::CreateComponentProperties(
      _fbb,
      binary_name__,
      application_profile,
      depends_on__,
      process_arguments__,
      ready_condition);
}

struct RestartAction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RestartActionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NUMBER_OF_ATTEMPTS = 4,
    VT_DELAY_BEFORE_RESTART = 6
  };
  uint32_t number_of_attempts() const {
    return GetField<uint32_t>(VT_NUMBER_OF_ATTEMPTS, 0);
  }
  double delay_before_restart() const {
    return GetField<double>(VT_DELAY_BEFORE_RESTART, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_NUMBER_OF_ATTEMPTS, 4) &&
           VerifyField<double>(verifier, VT_DELAY_BEFORE_RESTART, 8) &&
           verifier.EndTable();
  }
};

struct RestartActionBuilder {
  typedef RestartAction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_number_of_attempts(uint32_t number_of_attempts) {
    fbb_.AddElement<uint32_t>(RestartAction::VT_NUMBER_OF_ATTEMPTS, number_of_attempts, 0);
  }
  void add_delay_before_restart(double delay_before_restart) {
    fbb_.AddElement<double>(RestartAction::VT_DELAY_BEFORE_RESTART, delay_before_restart, 0.0);
  }
  explicit RestartActionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RestartAction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RestartAction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RestartAction> CreateRestartAction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t number_of_attempts = 0,
    double delay_before_restart = 0.0) {
  RestartActionBuilder builder_(_fbb);
  builder_.add_delay_before_restart(delay_before_restart);
  builder_.add_number_of_attempts(number_of_attempts);
  return builder_.Finish();
}

struct SwitchRunTargetAction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SwitchRunTargetActionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RUN_TARGET = 4
  };
  const ::flatbuffers::String *run_target() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RUN_TARGET);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_RUN_TARGET) &&
           verifier.VerifyString(run_target()) &&
           verifier.EndTable();
  }
};

struct SwitchRunTargetActionBuilder {
  typedef SwitchRunTargetAction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_run_target(::flatbuffers::Offset<::flatbuffers::String> run_target) {
    fbb_.AddOffset(SwitchRunTargetAction::VT_RUN_TARGET, run_target);
  }
  explicit SwitchRunTargetActionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SwitchRunTargetAction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SwitchRunTargetAction>(end);
    fbb_.Required(o, SwitchRunTargetAction::VT_RUN_TARGET);
    return o;
  }
};

inline ::flatbuffers::Offset<SwitchRunTargetAction> CreateSwitchRunTargetAction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> run_target = 0) {
  SwitchRunTargetActionBuilder builder_(_fbb);
  builder_.add_run_target(run_target);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SwitchRunTargetAction> CreateSwitchRunTargetActionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *run_target = nullptr) {
  auto run_target__ = run_target ? _fbb.CreateString(run_target) : 0;
  return score::launch_manager::config::fb::CreateSwitchRunTargetAction(
      _fbb,
      run_target__);
}

struct EnvironmentalVariable FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EnvironmentalVariableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffsetRequired(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct EnvironmentalVariableBuilder {
  typedef EnvironmentalVariable Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(EnvironmentalVariable::VT_KEY, key);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(EnvironmentalVariable::VT_VALUE, value);
  }
  explicit EnvironmentalVariableBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EnvironmentalVariable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EnvironmentalVariable>(end);
    fbb_.Required(o, EnvironmentalVariable::VT_KEY);
    fbb_.Required(o, EnvironmentalVariable::VT_VALUE);
    return o;
  }
};

inline ::flatbuffers::Offset<EnvironmentalVariable> CreateEnvironmentalVariable(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  EnvironmentalVariableBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EnvironmentalVariable> CreateEnvironmentalVariableDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const char *value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return score::launch_manager::config::fb::CreateEnvironmentalVariable(
      _fbb,
      key__,
      value__);
}

struct Sandbox FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SandboxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4,
    VT_GID = 6,
    VT_SUPPLEMENTARY_GROUP_IDS = 8,
    VT_SECURITY_POLICY = 10,
    VT_SCHEDULING_POLICY = 12,
    VT_SCHEDULING_PRIORITY = 14,
    VT_MAX_MEMORY_USAGE = 16,
    VT_MAX_CPU_USAGE = 18
  };
  uint32_t uid() const {
    return GetField<uint32_t>(VT_UID, 0);
  }
  uint32_t gid() const {
    return GetField<uint32_t>(VT_GID, 0);
  }
  const ::flatbuffers::Vector<uint32_t> *supplementary_group_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SUPPLEMENTARY_GROUP_IDS);
  }
  const ::flatbuffers::String *security_policy() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SECURITY_POLICY);
  }
  const ::flatbuffers::String *scheduling_policy() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SCHEDULING_POLICY);
  }
  ::flatbuffers::Optional<int32_t> scheduling_priority() const {
    return GetOptional<int32_t, int32_t>(VT_SCHEDULING_PRIORITY);
  }
  ::flatbuffers::Optional<uint64_t> max_memory_usage() const {
    return GetOptional<uint64_t, uint64_t>(VT_MAX_MEMORY_USAGE);
  }
  ::flatbuffers::Optional<uint32_t> max_cpu_usage() const {
    return GetOptional<uint32_t, uint32_t>(VT_MAX_CPU_USAGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_UID, 4) &&
           VerifyField<uint32_t>(verifier, VT_GID, 4) &&
           VerifyOffset(verifier, VT_SUPPLEMENTARY_GROUP_IDS) &&
           verifier.VerifyVector(supplementary_group_ids()) &&
           VerifyOffset(verifier, VT_SECURITY_POLICY) &&
           verifier.VerifyString(security_policy()) &&
           VerifyOffset(verifier, VT_SCHEDULING_POLICY) &&
           verifier.VerifyString(scheduling_policy()) &&
           VerifyField<int32_t>(verifier, VT_SCHEDULING_PRIORITY, 4) &&
           VerifyField<uint64_t>(verifier, VT_MAX_MEMORY_USAGE, 8) &&
           VerifyField<uint32_t>(verifier, VT_MAX_CPU_USAGE, 4) &&
           verifier.EndTable();
  }
};

struct SandboxBuilder {
  typedef Sandbox Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uid(uint32_t uid) {
    fbb_.AddElement<uint32_t>(Sandbox::VT_UID, uid, 0);
  }
  void add_gid(uint32_t gid) {
    fbb_.AddElement<uint32_t>(Sandbox::VT_GID, gid, 0);
  }
  void add_supplementary_group_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> supplementary_group_ids) {
    fbb_.AddOffset(Sandbox::VT_SUPPLEMENTARY_GROUP_IDS, supplementary_group_ids);
  }
  void add_security_policy(::flatbuffers::Offset<::flatbuffers::String> security_policy) {
    fbb_.AddOffset(Sandbox::VT_SECURITY_POLICY, security_policy);
  }
  void add_scheduling_policy(::flatbuffers::Offset<::flatbuffers::String> scheduling_policy) {
    fbb_.AddOffset(Sandbox::VT_SCHEDULING_POLICY, scheduling_policy);
  }
  void add_scheduling_priority(int32_t scheduling_priority) {
    fbb_.AddElement<int32_t>(Sandbox::VT_SCHEDULING_PRIORITY, scheduling_priority);
  }
  void add_max_memory_usage(uint64_t max_memory_usage) {
    fbb_.AddElement<uint64_t>(Sandbox::VT_MAX_MEMORY_USAGE, max_memory_usage);
  }
  void add_max_cpu_usage(uint32_t max_cpu_usage) {
    fbb_.AddElement<uint32_t>(Sandbox::VT_MAX_CPU_USAGE, max_cpu_usage);
  }
  explicit SandboxBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Sandbox> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Sandbox>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Sandbox> CreateSandbox(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t uid = 0,
    uint32_t gid = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> supplementary_group_ids = 0,
    ::flatbuffers::Offset<::flatbuffers::String> security_policy = 0,
    ::flatbuffers::Offset<::flatbuffers::String> scheduling_policy = 0,
    ::flatbuffers::Optional<int32_t> scheduling_priority = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint64_t> max_memory_usage = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint32_t> max_cpu_usage = ::flatbuffers::nullopt) {
  SandboxBuilder builder_(_fbb);
  if(max_memory_usage) { builder_.add_max_memory_usage(*max_memory_usage); }
  if(max_cpu_usage) { builder_.add_max_cpu_usage(*max_cpu_usage); }
  if(scheduling_priority) { builder_.add_scheduling_priority(*scheduling_priority); }
  builder_.add_scheduling_policy(scheduling_policy);
  builder_.add_security_policy(security_policy);
  builder_.add_supplementary_group_ids(supplementary_group_ids);
  builder_.add_gid(gid);
  builder_.add_uid(uid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Sandbox> CreateSandboxDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t uid = 0,
    uint32_t gid = 0,
    const std::vector<uint32_t> *supplementary_group_ids = nullptr,
    const char *security_policy = nullptr,
    const char *scheduling_policy = nullptr,
    ::flatbuffers::Optional<int32_t> scheduling_priority = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint64_t> max_memory_usage = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint32_t> max_cpu_usage = ::flatbuffers::nullopt) {
  auto supplementary_group_ids__ = supplementary_group_ids ? _fbb.CreateVector<uint32_t>(*supplementary_group_ids) : 0;
  auto security_policy__ = security_policy ? _fbb.CreateString(security_policy) : 0;
  auto scheduling_policy__ = scheduling_policy ? _fbb.CreateString(scheduling_policy) : 0;
  return score::launch_manager::config::fb::CreateSandbox(
      _fbb,
      uid,
      gid,
      supplementary_group_ids__,
      security_policy__,
      scheduling_policy__,
      scheduling_priority,
      max_memory_usage,
      max_cpu_usage);
}

struct DeploymentConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeploymentConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_READY_TIMEOUT = 4,
    VT_SHUTDOWN_TIMEOUT = 6,
    VT_ENVIRONMENTAL_VARIABLES = 8,
    VT_BIN_DIR = 10,
    VT_WORKING_DIR = 12,
    VT_READY_RECOVERY_ACTION_TYPE = 14,
    VT_READY_RECOVERY_ACTION = 16,
    VT_RECOVERY_ACTION_TYPE = 18,
    VT_RECOVERY_ACTION = 20,
    VT_SANDBOX = 22
  };
  double ready_timeout() const {
    return GetField<double>(VT_READY_TIMEOUT, 0.0);
  }
  double shutdown_timeout() const {
    return GetField<double>(VT_SHUTDOWN_TIMEOUT, 0.0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::EnvironmentalVariable>> *environmental_variables() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::EnvironmentalVariable>> *>(VT_ENVIRONMENTAL_VARIABLES);
  }
  const ::flatbuffers::String *bin_dir() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BIN_DIR);
  }
  const ::flatbuffers::String *working_dir() const {
    return GetPointer<const ::flatbuffers::String *>(VT_WORKING_DIR);
  }
  score::launch_manager::config::fb::RecoveryAction ready_recovery_action_type() const {
    return static_cast<score::launch_manager::config::fb::RecoveryAction>(GetField<uint8_t>(VT_READY_RECOVERY_ACTION_TYPE, 0));
  }
  const void *ready_recovery_action() const {
    return GetPointer<const void *>(VT_READY_RECOVERY_ACTION);
  }
  template<typename T> const T *ready_recovery_action_as() const;
  const score::launch_manager::config::fb::RestartAction *ready_recovery_action_as_RestartAction() const {
    return ready_recovery_action_type() == score::launch_manager::config::fb::RecoveryAction_RestartAction ? static_cast<const score::launch_manager::config::fb::RestartAction *>(ready_recovery_action()) : nullptr;
  }
  const score::launch_manager::config::fb::SwitchRunTargetAction *ready_recovery_action_as_SwitchRunTargetAction() const {
    return ready_recovery_action_type() == score::launch_manager::config::fb::RecoveryAction_SwitchRunTargetAction ? static_cast<const score::launch_manager::config::fb::SwitchRunTargetAction *>(ready_recovery_action()) : nullptr;
  }
  score::launch_manager::config::fb::RecoveryAction recovery_action_type() const {
    return static_cast<score::launch_manager::config::fb::RecoveryAction>(GetField<uint8_t>(VT_RECOVERY_ACTION_TYPE, 0));
  }
  const void *recovery_action() const {
    return GetPointer<const void *>(VT_RECOVERY_ACTION);
  }
  template<typename T> const T *recovery_action_as() const;
  const score::launch_manager::config::fb::RestartAction *recovery_action_as_RestartAction() const {
    return recovery_action_type() == score::launch_manager::config::fb::RecoveryAction_RestartAction ? static_cast<const score::launch_manager::config::fb::RestartAction *>(recovery_action()) : nullptr;
  }
  const score::launch_manager::config::fb::SwitchRunTargetAction *recovery_action_as_SwitchRunTargetAction() const {
    return recovery_action_type() == score::launch_manager::config::fb::RecoveryAction_SwitchRunTargetAction ? static_cast<const score::launch_manager::config::fb::SwitchRunTargetAction *>(recovery_action()) : nullptr;
  }
  const score::launch_manager::config::fb::Sandbox *sandbox() const {
    return GetPointer<const score::launch_manager::config::fb::Sandbox *>(VT_SANDBOX);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_READY_TIMEOUT, 8) &&
           VerifyField<double>(verifier, VT_SHUTDOWN_TIMEOUT, 8) &&
           VerifyOffset(verifier, VT_ENVIRONMENTAL_VARIABLES) &&
           verifier.VerifyVector(environmental_variables()) &&
           verifier.VerifyVectorOfTables(environmental_variables()) &&
           VerifyOffsetRequired(verifier, VT_BIN_DIR) &&
           verifier.VerifyString(bin_dir()) &&
           VerifyOffset(verifier, VT_WORKING_DIR) &&
           verifier.VerifyString(working_dir()) &&
           VerifyField<uint8_t>(verifier, VT_READY_RECOVERY_ACTION_TYPE, 1) &&
           VerifyOffset(verifier, VT_READY_RECOVERY_ACTION) &&
           VerifyRecoveryAction(verifier, ready_recovery_action(), ready_recovery_action_type()) &&
           VerifyField<uint8_t>(verifier, VT_RECOVERY_ACTION_TYPE, 1) &&
           VerifyOffset(verifier, VT_RECOVERY_ACTION) &&
           VerifyRecoveryAction(verifier, recovery_action(), recovery_action_type()) &&
           VerifyOffset(verifier, VT_SANDBOX) &&
           verifier.VerifyTable(sandbox()) &&
           verifier.EndTable();
  }
};

template<> inline const score::launch_manager::config::fb::RestartAction *DeploymentConfig::ready_recovery_action_as<score::launch_manager::config::fb::RestartAction>() const {
  return ready_recovery_action_as_RestartAction();
}

template<> inline const score::launch_manager::config::fb::SwitchRunTargetAction *DeploymentConfig::ready_recovery_action_as<score::launch_manager::config::fb::SwitchRunTargetAction>() const {
  return ready_recovery_action_as_SwitchRunTargetAction();
}

template<> inline const score::launch_manager::config::fb::RestartAction *DeploymentConfig::recovery_action_as<score::launch_manager::config::fb::RestartAction>() const {
  return recovery_action_as_RestartAction();
}

template<> inline const score::launch_manager::config::fb::SwitchRunTargetAction *DeploymentConfig::recovery_action_as<score::launch_manager::config::fb::SwitchRunTargetAction>() const {
  return recovery_action_as_SwitchRunTargetAction();
}

struct DeploymentConfigBuilder {
  typedef DeploymentConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ready_timeout(double ready_timeout) {
    fbb_.AddElement<double>(DeploymentConfig::VT_READY_TIMEOUT, ready_timeout, 0.0);
  }
  void add_shutdown_timeout(double shutdown_timeout) {
    fbb_.AddElement<double>(DeploymentConfig::VT_SHUTDOWN_TIMEOUT, shutdown_timeout, 0.0);
  }
  void add_environmental_variables(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::EnvironmentalVariable>>> environmental_variables) {
    fbb_.AddOffset(DeploymentConfig::VT_ENVIRONMENTAL_VARIABLES, environmental_variables);
  }
  void add_bin_dir(::flatbuffers::Offset<::flatbuffers::String> bin_dir) {
    fbb_.AddOffset(DeploymentConfig::VT_BIN_DIR, bin_dir);
  }
  void add_working_dir(::flatbuffers::Offset<::flatbuffers::String> working_dir) {
    fbb_.AddOffset(DeploymentConfig::VT_WORKING_DIR, working_dir);
  }
  void add_ready_recovery_action_type(score::launch_manager::config::fb::RecoveryAction ready_recovery_action_type) {
    fbb_.AddElement<uint8_t>(DeploymentConfig::VT_READY_RECOVERY_ACTION_TYPE, static_cast<uint8_t>(ready_recovery_action_type), 0);
  }
  void add_ready_recovery_action(::flatbuffers::Offset<void> ready_recovery_action) {
    fbb_.AddOffset(DeploymentConfig::VT_READY_RECOVERY_ACTION, ready_recovery_action);
  }
  void add_recovery_action_type(score::launch_manager::config::fb::RecoveryAction recovery_action_type) {
    fbb_.AddElement<uint8_t>(DeploymentConfig::VT_RECOVERY_ACTION_TYPE, static_cast<uint8_t>(recovery_action_type), 0);
  }
  void add_recovery_action(::flatbuffers::Offset<void> recovery_action) {
    fbb_.AddOffset(DeploymentConfig::VT_RECOVERY_ACTION, recovery_action);
  }
  void add_sandbox(::flatbuffers::Offset<score::launch_manager::config::fb::Sandbox> sandbox) {
    fbb_.AddOffset(DeploymentConfig::VT_SANDBOX, sandbox);
  }
  explicit DeploymentConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeploymentConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeploymentConfig>(end);
    fbb_.Required(o, DeploymentConfig::VT_BIN_DIR);
    return o;
  }
};

inline ::flatbuffers::Offset<DeploymentConfig> CreateDeploymentConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double ready_timeout = 0.0,
    double shutdown_timeout = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::EnvironmentalVariable>>> environmental_variables = 0,
    ::flatbuffers::Offset<::flatbuffers::String> bin_dir = 0,
    ::flatbuffers::Offset<::flatbuffers::String> working_dir = 0,
    score::launch_manager::config::fb::RecoveryAction ready_recovery_action_type = score::launch_manager::config::fb::RecoveryAction_NONE,
    ::flatbuffers::Offset<void> ready_recovery_action = 0,
    score::launch_manager::config::fb::RecoveryAction recovery_action_type = score::launch_manager::config::fb::RecoveryAction_NONE,
    ::flatbuffers::Offset<void> recovery_action = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::Sandbox> sandbox = 0) {
  DeploymentConfigBuilder builder_(_fbb);
  builder_.add_shutdown_timeout(shutdown_timeout);
  builder_.add_ready_timeout(ready_timeout);
  builder_.add_sandbox(sandbox);
  builder_.add_recovery_action(recovery_action);
  builder_.add_ready_recovery_action(ready_recovery_action);
  builder_.add_working_dir(working_dir);
  builder_.add_bin_dir(bin_dir);
  builder_.add_environmental_variables(environmental_variables);
  builder_.add_recovery_action_type(recovery_action_type);
  builder_.add_ready_recovery_action_type(ready_recovery_action_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeploymentConfig> CreateDeploymentConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double ready_timeout = 0.0,
    double shutdown_timeout = 0.0,
    const std::vector<::flatbuffers::Offset<score::launch_manager::config::fb::EnvironmentalVariable>> *environmental_variables = nullptr,
    const char *bin_dir = nullptr,
    const char *working_dir = nullptr,
    score::launch_manager::config::fb::RecoveryAction ready_recovery_action_type = score::launch_manager::config::fb::RecoveryAction_NONE,
    ::flatbuffers::Offset<void> ready_recovery_action = 0,
    score::launch_manager::config::fb::RecoveryAction recovery_action_type = score::launch_manager::config::fb::RecoveryAction_NONE,
    ::flatbuffers::Offset<void> recovery_action = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::Sandbox> sandbox = 0) {
  auto environmental_variables__ = environmental_variables ? _fbb.CreateVector<::flatbuffers::Offset<score::launch_manager::config::fb::EnvironmentalVariable>>(*environmental_variables) : 0;
  auto bin_dir__ = bin_dir ? _fbb.CreateString(bin_dir) : 0;
  auto working_dir__ = working_dir ? _fbb.CreateString(working_dir) : 0;
  return score::launch_manager::config::fb::CreateDeploymentConfig(
      _fbb,
      ready_timeout,
      shutdown_timeout,
      environmental_variables__,
      bin_dir__,
      working_dir__,
      ready_recovery_action_type,
      ready_recovery_action,
      recovery_action_type,
      recovery_action,
      sandbox);
}

struct RunTarget FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RunTargetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DESCRIPTION = 6,
    VT_DEPENDS_ON = 8,
    VT_TRANSITION_TIMEOUT = 10,
    VT_RECOVERY_ACTION_TYPE = 12,
    VT_RECOVERY_ACTION = 14
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *depends_on() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DEPENDS_ON);
  }
  double transition_timeout() const {
    return GetField<double>(VT_TRANSITION_TIMEOUT, 0.0);
  }
  score::launch_manager::config::fb::RecoveryAction recovery_action_type() const {
    return static_cast<score::launch_manager::config::fb::RecoveryAction>(GetField<uint8_t>(VT_RECOVERY_ACTION_TYPE, 0));
  }
  const void *recovery_action() const {
    return GetPointer<const void *>(VT_RECOVERY_ACTION);
  }
  template<typename T> const T *recovery_action_as() const;
  const score::launch_manager::config::fb::RestartAction *recovery_action_as_RestartAction() const {
    return recovery_action_type() == score::launch_manager::config::fb::RecoveryAction_RestartAction ? static_cast<const score::launch_manager::config::fb::RestartAction *>(recovery_action()) : nullptr;
  }
  const score::launch_manager::config::fb::SwitchRunTargetAction *recovery_action_as_SwitchRunTargetAction() const {
    return recovery_action_type() == score::launch_manager::config::fb::RecoveryAction_SwitchRunTargetAction ? static_cast<const score::launch_manager::config::fb::SwitchRunTargetAction *>(recovery_action()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_DEPENDS_ON) &&
           verifier.VerifyVector(depends_on()) &&
           verifier.VerifyVectorOfStrings(depends_on()) &&
           VerifyField<double>(verifier, VT_TRANSITION_TIMEOUT, 8) &&
           VerifyField<uint8_t>(verifier, VT_RECOVERY_ACTION_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_RECOVERY_ACTION) &&
           VerifyRecoveryAction(verifier, recovery_action(), recovery_action_type()) &&
           verifier.EndTable();
  }
};

template<> inline const score::launch_manager::config::fb::RestartAction *RunTarget::recovery_action_as<score::launch_manager::config::fb::RestartAction>() const {
  return recovery_action_as_RestartAction();
}

template<> inline const score::launch_manager::config::fb::SwitchRunTargetAction *RunTarget::recovery_action_as<score::launch_manager::config::fb::SwitchRunTargetAction>() const {
  return recovery_action_as_SwitchRunTargetAction();
}

struct RunTargetBuilder {
  typedef RunTarget Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(RunTarget::VT_NAME, name);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(RunTarget::VT_DESCRIPTION, description);
  }
  void add_depends_on(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> depends_on) {
    fbb_.AddOffset(RunTarget::VT_DEPENDS_ON, depends_on);
  }
  void add_transition_timeout(double transition_timeout) {
    fbb_.AddElement<double>(RunTarget::VT_TRANSITION_TIMEOUT, transition_timeout, 0.0);
  }
  void add_recovery_action_type(score::launch_manager::config::fb::RecoveryAction recovery_action_type) {
    fbb_.AddElement<uint8_t>(RunTarget::VT_RECOVERY_ACTION_TYPE, static_cast<uint8_t>(recovery_action_type), 0);
  }
  void add_recovery_action(::flatbuffers::Offset<void> recovery_action) {
    fbb_.AddOffset(RunTarget::VT_RECOVERY_ACTION, recovery_action);
  }
  explicit RunTargetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RunTarget> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RunTarget>(end);
    fbb_.Required(o, RunTarget::VT_NAME);
    fbb_.Required(o, RunTarget::VT_RECOVERY_ACTION);
    return o;
  }
};

inline ::flatbuffers::Offset<RunTarget> CreateRunTarget(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> depends_on = 0,
    double transition_timeout = 0.0,
    score::launch_manager::config::fb::RecoveryAction recovery_action_type = score::launch_manager::config::fb::RecoveryAction_NONE,
    ::flatbuffers::Offset<void> recovery_action = 0) {
  RunTargetBuilder builder_(_fbb);
  builder_.add_transition_timeout(transition_timeout);
  builder_.add_recovery_action(recovery_action);
  builder_.add_depends_on(depends_on);
  builder_.add_description(description);
  builder_.add_name(name);
  builder_.add_recovery_action_type(recovery_action_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RunTarget> CreateRunTargetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *description = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *depends_on = nullptr,
    double transition_timeout = 0.0,
    score::launch_manager::config::fb::RecoveryAction recovery_action_type = score::launch_manager::config::fb::RecoveryAction_NONE,
    ::flatbuffers::Offset<void> recovery_action = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto depends_on__ = depends_on ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*depends_on) : 0;
  return score::launch_manager::config::fb::CreateRunTarget(
      _fbb,
      name__,
      description__,
      depends_on__,
      transition_timeout,
      recovery_action_type,
      recovery_action);
}

struct Component FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ComponentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DESCRIPTION = 6,
    VT_COMPONENT_PROPERTIES = 8,
    VT_DEPLOYMENT_CONFIG = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  const score::launch_manager::config::fb::ComponentProperties *component_properties() const {
    return GetPointer<const score::launch_manager::config::fb::ComponentProperties *>(VT_COMPONENT_PROPERTIES);
  }
  const score::launch_manager::config::fb::DeploymentConfig *deployment_config() const {
    return GetPointer<const score::launch_manager::config::fb::DeploymentConfig *>(VT_DEPLOYMENT_CONFIG);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffsetRequired(verifier, VT_COMPONENT_PROPERTIES) &&
           verifier.VerifyTable(component_properties()) &&
           VerifyOffsetRequired(verifier, VT_DEPLOYMENT_CONFIG) &&
           verifier.VerifyTable(deployment_config()) &&
           verifier.EndTable();
  }
};

struct ComponentBuilder {
  typedef Component Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Component::VT_NAME, name);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(Component::VT_DESCRIPTION, description);
  }
  void add_component_properties(::flatbuffers::Offset<score::launch_manager::config::fb::ComponentProperties> component_properties) {
    fbb_.AddOffset(Component::VT_COMPONENT_PROPERTIES, component_properties);
  }
  void add_deployment_config(::flatbuffers::Offset<score::launch_manager::config::fb::DeploymentConfig> deployment_config) {
    fbb_.AddOffset(Component::VT_DEPLOYMENT_CONFIG, deployment_config);
  }
  explicit ComponentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Component> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Component>(end);
    fbb_.Required(o, Component::VT_NAME);
    fbb_.Required(o, Component::VT_COMPONENT_PROPERTIES);
    fbb_.Required(o, Component::VT_DEPLOYMENT_CONFIG);
    return o;
  }
};

inline ::flatbuffers::Offset<Component> CreateComponent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::ComponentProperties> component_properties = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::DeploymentConfig> deployment_config = 0) {
  ComponentBuilder builder_(_fbb);
  builder_.add_deployment_config(deployment_config);
  builder_.add_component_properties(component_properties);
  builder_.add_description(description);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Component> CreateComponentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *description = nullptr,
    ::flatbuffers::Offset<score::launch_manager::config::fb::ComponentProperties> component_properties = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::DeploymentConfig> deployment_config = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return score::launch_manager::config::fb::CreateComponent(
      _fbb,
      name__,
      description__,
      component_properties,
      deployment_config);
}

struct AliveSupervision FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AliveSupervisionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVALUATION_CYCLE = 4
  };
  double evaluation_cycle() const {
    return GetField<double>(VT_EVALUATION_CYCLE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_EVALUATION_CYCLE, 8) &&
           verifier.EndTable();
  }
};

struct AliveSupervisionBuilder {
  typedef AliveSupervision Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_evaluation_cycle(double evaluation_cycle) {
    fbb_.AddElement<double>(AliveSupervision::VT_EVALUATION_CYCLE, evaluation_cycle, 0.0);
  }
  explicit AliveSupervisionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AliveSupervision> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AliveSupervision>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AliveSupervision> CreateAliveSupervision(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double evaluation_cycle = 0.0) {
  AliveSupervisionBuilder builder_(_fbb);
  builder_.add_evaluation_cycle(evaluation_cycle);
  return builder_.Finish();
}

struct Watchdog FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WatchdogBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEVICE_FILE_PATH = 4,
    VT_MAX_TIMEOUT = 6,
    VT_DEACTIVATE_ON_SHUTDOWN = 8,
    VT_REQUIRE_MAGIC_CLOSE = 10
  };
  const ::flatbuffers::String *device_file_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_FILE_PATH);
  }
  double max_timeout() const {
    return GetField<double>(VT_MAX_TIMEOUT, 0.0);
  }
  ::flatbuffers::Optional<bool> deactivate_on_shutdown() const {
    return GetOptional<uint8_t, bool>(VT_DEACTIVATE_ON_SHUTDOWN);
  }
  ::flatbuffers::Optional<bool> require_magic_close() const {
    return GetOptional<uint8_t, bool>(VT_REQUIRE_MAGIC_CLOSE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DEVICE_FILE_PATH) &&
           verifier.VerifyString(device_file_path()) &&
           VerifyField<double>(verifier, VT_MAX_TIMEOUT, 8) &&
           VerifyField<uint8_t>(verifier, VT_DEACTIVATE_ON_SHUTDOWN, 1) &&
           VerifyField<uint8_t>(verifier, VT_REQUIRE_MAGIC_CLOSE, 1) &&
           verifier.EndTable();
  }
};

struct WatchdogBuilder {
  typedef Watchdog Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_device_file_path(::flatbuffers::Offset<::flatbuffers::String> device_file_path) {
    fbb_.AddOffset(Watchdog::VT_DEVICE_FILE_PATH, device_file_path);
  }
  void add_max_timeout(double max_timeout) {
    fbb_.AddElement<double>(Watchdog::VT_MAX_TIMEOUT, max_timeout, 0.0);
  }
  void add_deactivate_on_shutdown(bool deactivate_on_shutdown) {
    fbb_.AddElement<uint8_t>(Watchdog::VT_DEACTIVATE_ON_SHUTDOWN, static_cast<uint8_t>(deactivate_on_shutdown));
  }
  void add_require_magic_close(bool require_magic_close) {
    fbb_.AddElement<uint8_t>(Watchdog::VT_REQUIRE_MAGIC_CLOSE, static_cast<uint8_t>(require_magic_close));
  }
  explicit WatchdogBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Watchdog> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Watchdog>(end);
    fbb_.Required(o, Watchdog::VT_DEVICE_FILE_PATH);
    return o;
  }
};

inline ::flatbuffers::Offset<Watchdog> CreateWatchdog(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> device_file_path = 0,
    double max_timeout = 0.0,
    ::flatbuffers::Optional<bool> deactivate_on_shutdown = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<bool> require_magic_close = ::flatbuffers::nullopt) {
  WatchdogBuilder builder_(_fbb);
  builder_.add_max_timeout(max_timeout);
  builder_.add_device_file_path(device_file_path);
  if(require_magic_close) { builder_.add_require_magic_close(*require_magic_close); }
  if(deactivate_on_shutdown) { builder_.add_deactivate_on_shutdown(*deactivate_on_shutdown); }
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Watchdog> CreateWatchdogDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *device_file_path = nullptr,
    double max_timeout = 0.0,
    ::flatbuffers::Optional<bool> deactivate_on_shutdown = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<bool> require_magic_close = ::flatbuffers::nullopt) {
  auto device_file_path__ = device_file_path ? _fbb.CreateString(device_file_path) : 0;
  return score::launch_manager::config::fb::CreateWatchdog(
      _fbb,
      device_file_path__,
      max_timeout,
      deactivate_on_shutdown,
      require_magic_close);
}

struct FallbackRunTarget FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FallbackRunTargetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DESCRIPTION = 4,
    VT_DEPENDS_ON = 6,
    VT_TRANSITION_TIMEOUT = 8
  };
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *depends_on() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DEPENDS_ON);
  }
  double transition_timeout() const {
    return GetField<double>(VT_TRANSITION_TIMEOUT, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_DEPENDS_ON) &&
           verifier.VerifyVector(depends_on()) &&
           verifier.VerifyVectorOfStrings(depends_on()) &&
           VerifyField<double>(verifier, VT_TRANSITION_TIMEOUT, 8) &&
           verifier.EndTable();
  }
};

struct FallbackRunTargetBuilder {
  typedef FallbackRunTarget Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(FallbackRunTarget::VT_DESCRIPTION, description);
  }
  void add_depends_on(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> depends_on) {
    fbb_.AddOffset(FallbackRunTarget::VT_DEPENDS_ON, depends_on);
  }
  void add_transition_timeout(double transition_timeout) {
    fbb_.AddElement<double>(FallbackRunTarget::VT_TRANSITION_TIMEOUT, transition_timeout, 0.0);
  }
  explicit FallbackRunTargetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FallbackRunTarget> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FallbackRunTarget>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FallbackRunTarget> CreateFallbackRunTarget(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> depends_on = 0,
    double transition_timeout = 0.0) {
  FallbackRunTargetBuilder builder_(_fbb);
  builder_.add_transition_timeout(transition_timeout);
  builder_.add_depends_on(depends_on);
  builder_.add_description(description);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FallbackRunTarget> CreateFallbackRunTargetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *description = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *depends_on = nullptr,
    double transition_timeout = 0.0) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto depends_on__ = depends_on ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*depends_on) : 0;
  return score::launch_manager::config::fb::CreateFallbackRunTarget(
      _fbb,
      description__,
      depends_on__,
      transition_timeout);
}

struct LaunchManagerConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LaunchManagerConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHEMA_VERSION = 4,
    VT_COMPONENTS = 6,
    VT_RUN_TARGETS = 8,
    VT_INITIAL_RUN_TARGET = 10,
    VT_FALLBACK_RUN_TARGET = 12,
    VT_ALIVE_SUPERVISION = 14,
    VT_WATCHDOG = 16
  };
  int32_t schema_version() const {
    return GetField<int32_t>(VT_SCHEMA_VERSION, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::Component>> *components() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::Component>> *>(VT_COMPONENTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::RunTarget>> *run_targets() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::RunTarget>> *>(VT_RUN_TARGETS);
  }
  const ::flatbuffers::String *initial_run_target() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INITIAL_RUN_TARGET);
  }
  const score::launch_manager::config::fb::FallbackRunTarget *fallback_run_target() const {
    return GetPointer<const score::launch_manager::config::fb::FallbackRunTarget *>(VT_FALLBACK_RUN_TARGET);
  }
  const score::launch_manager::config::fb::AliveSupervision *alive_supervision() const {
    return GetPointer<const score::launch_manager::config::fb::AliveSupervision *>(VT_ALIVE_SUPERVISION);
  }
  const score::launch_manager::config::fb::Watchdog *watchdog() const {
    return GetPointer<const score::launch_manager::config::fb::Watchdog *>(VT_WATCHDOG);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           VerifyOffset(verifier, VT_COMPONENTS) &&
           verifier.VerifyVector(components()) &&
           verifier.VerifyVectorOfTables(components()) &&
           VerifyOffset(verifier, VT_RUN_TARGETS) &&
           verifier.VerifyVector(run_targets()) &&
           verifier.VerifyVectorOfTables(run_targets()) &&
           VerifyOffsetRequired(verifier, VT_INITIAL_RUN_TARGET) &&
           verifier.VerifyString(initial_run_target()) &&
           VerifyOffsetRequired(verifier, VT_FALLBACK_RUN_TARGET) &&
           verifier.VerifyTable(fallback_run_target()) &&
           VerifyOffsetRequired(verifier, VT_ALIVE_SUPERVISION) &&
           verifier.VerifyTable(alive_supervision()) &&
           VerifyOffset(verifier, VT_WATCHDOG) &&
           verifier.VerifyTable(watchdog()) &&
           verifier.EndTable();
  }
};

struct LaunchManagerConfigBuilder {
  typedef LaunchManagerConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schema_version(int32_t schema_version) {
    fbb_.AddElement<int32_t>(LaunchManagerConfig::VT_SCHEMA_VERSION, schema_version, 0);
  }
  void add_components(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::Component>>> components) {
    fbb_.AddOffset(LaunchManagerConfig::VT_COMPONENTS, components);
  }
  void add_run_targets(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::RunTarget>>> run_targets) {
    fbb_.AddOffset(LaunchManagerConfig::VT_RUN_TARGETS, run_targets);
  }
  void add_initial_run_target(::flatbuffers::Offset<::flatbuffers::String> initial_run_target) {
    fbb_.AddOffset(LaunchManagerConfig::VT_INITIAL_RUN_TARGET, initial_run_target);
  }
  void add_fallback_run_target(::flatbuffers::Offset<score::launch_manager::config::fb::FallbackRunTarget> fallback_run_target) {
    fbb_.AddOffset(LaunchManagerConfig::VT_FALLBACK_RUN_TARGET, fallback_run_target);
  }
  void add_alive_supervision(::flatbuffers::Offset<score::launch_manager::config::fb::AliveSupervision> alive_supervision) {
    fbb_.AddOffset(LaunchManagerConfig::VT_ALIVE_SUPERVISION, alive_supervision);
  }
  void add_watchdog(::flatbuffers::Offset<score::launch_manager::config::fb::Watchdog> watchdog) {
    fbb_.AddOffset(LaunchManagerConfig::VT_WATCHDOG, watchdog);
  }
  explicit LaunchManagerConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LaunchManagerConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LaunchManagerConfig>(end);
    fbb_.Required(o, LaunchManagerConfig::VT_INITIAL_RUN_TARGET);
    fbb_.Required(o, LaunchManagerConfig::VT_FALLBACK_RUN_TARGET);
    fbb_.Required(o, LaunchManagerConfig::VT_ALIVE_SUPERVISION);
    return o;
  }
};

inline ::flatbuffers::Offset<LaunchManagerConfig> CreateLaunchManagerConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t schema_version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::Component>>> components = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<score::launch_manager::config::fb::RunTarget>>> run_targets = 0,
    ::flatbuffers::Offset<::flatbuffers::String> initial_run_target = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::FallbackRunTarget> fallback_run_target = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::AliveSupervision> alive_supervision = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::Watchdog> watchdog = 0) {
  LaunchManagerConfigBuilder builder_(_fbb);
  builder_.add_watchdog(watchdog);
  builder_.add_alive_supervision(alive_supervision);
  builder_.add_fallback_run_target(fallback_run_target);
  builder_.add_initial_run_target(initial_run_target);
  builder_.add_run_targets(run_targets);
  builder_.add_components(components);
  builder_.add_schema_version(schema_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LaunchManagerConfig> CreateLaunchManagerConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t schema_version = 0,
    const std::vector<::flatbuffers::Offset<score::launch_manager::config::fb::Component>> *components = nullptr,
    const std::vector<::flatbuffers::Offset<score::launch_manager::config::fb::RunTarget>> *run_targets = nullptr,
    const char *initial_run_target = nullptr,
    ::flatbuffers::Offset<score::launch_manager::config::fb::FallbackRunTarget> fallback_run_target = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::AliveSupervision> alive_supervision = 0,
    ::flatbuffers::Offset<score::launch_manager::config::fb::Watchdog> watchdog = 0) {
  auto components__ = components ? _fbb.CreateVector<::flatbuffers::Offset<score::launch_manager::config::fb::Component>>(*components) : 0;
  auto run_targets__ = run_targets ? _fbb.CreateVector<::flatbuffers::Offset<score::launch_manager::config::fb::RunTarget>>(*run_targets) : 0;
  auto initial_run_target__ = initial_run_target ? _fbb.CreateString(initial_run_target) : 0;
  return score::launch_manager::config::fb::CreateLaunchManagerConfig(
      _fbb,
      schema_version,
      components__,
      run_targets__,
      initial_run_target__,
      fallback_run_target,
      alive_supervision,
      watchdog);
}

template <bool B>
inline bool VerifyRecoveryAction(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, RecoveryAction type) {
  switch (type) {
    case RecoveryAction_NONE: {
      return true;
    }
    case RecoveryAction_RestartAction: {
      auto ptr = reinterpret_cast<const score::launch_manager::config::fb::RestartAction *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RecoveryAction_SwitchRunTargetAction: {
      auto ptr = reinterpret_cast<const score::launch_manager::config::fb::SwitchRunTargetAction *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyRecoveryActionVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRecoveryAction(
        verifier,  values->Get(i), types->GetEnum<RecoveryAction>(i))) {
      return false;
    }
  }
  return true;
}

inline const score::launch_manager::config::fb::LaunchManagerConfig *GetLaunchManagerConfig(const void *buf) {
  return ::flatbuffers::GetRoot<score::launch_manager::config::fb::LaunchManagerConfig>(buf);
}

inline const score::launch_manager::config::fb::LaunchManagerConfig *GetSizePrefixedLaunchManagerConfig(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<score::launch_manager::config::fb::LaunchManagerConfig>(buf);
}

template <bool B = false>
inline bool VerifyLaunchManagerConfigBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<score::launch_manager::config::fb::LaunchManagerConfig>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedLaunchManagerConfigBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<score::launch_manager::config::fb::LaunchManagerConfig>(nullptr);
}

inline void FinishLaunchManagerConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<score::launch_manager::config::fb::LaunchManagerConfig> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLaunchManagerConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<score::launch_manager::config::fb::LaunchManagerConfig> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fb
}  // namespace config
}  // namespace launch_manager
}  // namespace score

#endif  // FLATBUFFERS_GENERATED_NEWLMFLATCFG_SCORE_LAUNCH_MANAGER_CONFIG_FB_H_
